[general]
import = ["colors/vscode-dark.toml"]
live_config_reload = true

[terminal]
shell = { program = "pwsh.exe" }
osc52 = "CopyPaste"

[window]
dimensions = { columns = 120, lines = 35 }
position = { x = 0, y = 0 }
decorations = "Full"
decorations_theme_variant = "None"
title = "Alacritty"
dynamic_padding = true
dynamic_title = true

[font]
normal = { family = "RobotoMono Nerd Font Mono", style = "Regular" }
bold = { family = "RobotoMono Nerd Font Mono", style = "Bold" }
italic = { family = "RobotoMono Nerd Font Mono", style = "Italic" }
size = 12.0

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
